### ISSUE TITLE
Error with Paper 1.20

### ISSUE THREAD

**Issue by Fail-Safe** [JNNGL/VanillaMinimaps#16]
This server is running Paper version git-Paper-17 (MC: 1.20) (Implementing API version 1.20-R0.1-SNAPSHOT) (Git: c287e92)

```
[17:26:58] [Server thread/INFO]: [VanillaMinimaps] Enabling VanillaMinimaps v1.0.0
[17:26:58] [Server thread/ERROR]: Error occurred while enabling VanillaMinimaps v1.0.0 (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/event/block/SculkBloomEvent
at com.jnngl.vanillaminimaps.listener.MinimapBlockListener.<clinit>(MinimapBlockListener.java:41) ~[vanillaminimaps-1.0.0.jar:?]
at com.jnngl.vanillaminimaps.VanillaMinimaps.onEnable(VanillaMinimaps.java:127) ~[vanillaminimaps-1.0.0.jar:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.jar:git-Paper-17]
at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.jar:git-Paper-17]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:562) ~[paper-1.20.jar:git-Paper-17]
at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:473) ~[paper-1.20.jar:git-Paper-17]
at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.20.jar:git-Paper-17]
at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435) ~[paper-1.20.jar:git-Paper-17]
at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.jar:git-Paper-17]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.20.jar:git-Paper-17]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.jar:git-Paper-17]
at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.event.block.SculkBloomEvent
at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:183) ~[paper-api-1.20-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:150) ~[paper-api-1.20-R0.1-SNAPSHOT.jar:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
... 14 more
[17:26:58] [Server thread/INFO]: [VanillaMinimaps] Disabling VanillaMinimaps v1.0.0
```

**Comment by JNNGL** [comment]
Currently the plugin is only compatible with 1.20.4. Probably won't be ported to older versions.
